// <auto-generated />
using System;
using MakeMeRich.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MakeMeRich.Infrastructure.Persistance.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201108212134_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MakeMeRich.Domain.Entities.FinancialAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(80)")
                        .HasMaxLength(80)
                        .IsUnicode(true);

                    b.HasKey("Id");

                    b.ToTable("FinancialAccounts");
                });

            modelBuilder.Entity("MakeMeRich.Domain.Entities.FinancialCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(80)")
                        .HasMaxLength(80)
                        .IsUnicode(true);

                    b.HasKey("Id");

                    b.ToTable("FinancialCategories");
                });

            modelBuilder.Entity("MakeMeRich.Domain.Entities.FinancialTransactionCategories.ExternalTransactionCategory", b =>
                {
                    b.Property<int>("ExternalTransactionId")
                        .HasColumnType("int");

                    b.Property<int>("FinancialCategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("ExternalTransactionId", "FinancialCategoryId");

                    b.HasIndex("FinancialCategoryId");

                    b.ToTable("ExternalTransactionCategories");
                });

            modelBuilder.Entity("MakeMeRich.Domain.Entities.FinancialTransactionCategories.InternalTransactionCategory", b =>
                {
                    b.Property<int>("InternalTransactionId")
                        .HasColumnType("int");

                    b.Property<int>("FinancialCategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("InternalTransactionId", "FinancialCategoryId");

                    b.HasIndex("FinancialCategoryId");

                    b.ToTable("InternalTransactionCategories");
                });

            modelBuilder.Entity("MakeMeRich.Domain.Entities.FinancialTransactions.ExternalTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("date");

                    b.Property<int>("FinancialAccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TransactionSideName")
                        .IsRequired()
                        .HasColumnType("nvarchar(80)")
                        .HasMaxLength(80)
                        .IsUnicode(true);

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FinancialAccountId");

                    b.ToTable("ExternalTransactions");
                });

            modelBuilder.Entity("MakeMeRich.Domain.Entities.FinancialTransactions.InternalTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("date");

                    b.Property<int>("ReceivingAccountId")
                        .HasColumnType("int");

                    b.Property<int>("SendingAccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ReceivingAccountId");

                    b.HasIndex("SendingAccountId");

                    b.ToTable("InternalTransactions");
                });

            modelBuilder.Entity("MakeMeRich.Domain.Entities.FinancialTransactionCategories.ExternalTransactionCategory", b =>
                {
                    b.HasOne("MakeMeRich.Domain.Entities.FinancialTransactions.ExternalTransaction", "ExternalTransaction")
                        .WithMany("TransactionCategories")
                        .HasForeignKey("ExternalTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MakeMeRich.Domain.Entities.FinancialCategory", "Category")
                        .WithMany("ExternalTransactionCategories")
                        .HasForeignKey("FinancialCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MakeMeRich.Domain.Entities.FinancialTransactionCategories.InternalTransactionCategory", b =>
                {
                    b.HasOne("MakeMeRich.Domain.Entities.FinancialCategory", "Category")
                        .WithMany("InternalTransactionCategories")
                        .HasForeignKey("FinancialCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MakeMeRich.Domain.Entities.FinancialTransactions.InternalTransaction", "InternalTransaction")
                        .WithMany("TransactionCategories")
                        .HasForeignKey("InternalTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MakeMeRich.Domain.Entities.FinancialTransactions.ExternalTransaction", b =>
                {
                    b.HasOne("MakeMeRich.Domain.Entities.FinancialAccount", "FinancialAccount")
                        .WithMany("ExternalTransactions")
                        .HasForeignKey("FinancialAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MakeMeRich.Domain.Entities.FinancialTransactions.InternalTransaction", b =>
                {
                    b.HasOne("MakeMeRich.Domain.Entities.FinancialAccount", "ReceivingAccount")
                        .WithMany("ReceivedInternalTransactions")
                        .HasForeignKey("ReceivingAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MakeMeRich.Domain.Entities.FinancialAccount", "SendingAccount")
                        .WithMany("SendedInternalTransactions")
                        .HasForeignKey("SendingAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
