// <auto-generated />
using System;
using MakeMeRich.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MakeMeRich.Infrastructure.Persistance.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201122185746_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("MakeMeRich.Domain.Entities.FinancialAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("FinancialAccounts");
                });

            modelBuilder.Entity("MakeMeRich.Domain.Entities.FinancialCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("FinancialCategories");
                });

            modelBuilder.Entity("MakeMeRich.Domain.Entities.FinancialTransactionCategories.ExternalTransactionCategory", b =>
                {
                    b.Property<int>("ExternalTransactionId")
                        .HasColumnType("int");

                    b.Property<int>("FinancialCategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ExternalTransactionId", "FinancialCategoryId");

                    b.HasIndex("FinancialCategoryId");

                    b.ToTable("ExternalTransactionCategories");
                });

            modelBuilder.Entity("MakeMeRich.Domain.Entities.FinancialTransactionCategories.InternalTransactionCategory", b =>
                {
                    b.Property<int>("InternalTransactionId")
                        .HasColumnType("int");

                    b.Property<int>("FinancialCategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("InternalTransactionId", "FinancialCategoryId");

                    b.HasIndex("FinancialCategoryId");

                    b.ToTable("InternalTransactionCategories");
                });

            modelBuilder.Entity("MakeMeRich.Domain.Entities.FinancialTransactions.ExternalTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("date");

                    b.Property<int>("FinancialAccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TransactionSideName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FinancialAccountId");

                    b.ToTable("ExternalTransactions");
                });

            modelBuilder.Entity("MakeMeRich.Domain.Entities.FinancialTransactions.InternalTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("date");

                    b.Property<int>("ReceivingAccountId")
                        .HasColumnType("int");

                    b.Property<int>("SendingAccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ReceivingAccountId");

                    b.HasIndex("SendingAccountId");

                    b.ToTable("InternalTransactions");

                    b.HasCheckConstraint("CHK_InternalTransactions_SendingAccountId", "SendingAccountId != ReceivingAccountId");

                    b.HasCheckConstraint("CHK_InternalTransactions_ReceivingAccountId", "ReceivingAccountId != SendingAccountId");
                });

            modelBuilder.Entity("MakeMeRich.Domain.Entities.FinancialTransactionCategories.ExternalTransactionCategory", b =>
                {
                    b.HasOne("MakeMeRich.Domain.Entities.FinancialTransactions.ExternalTransaction", "ExternalTransaction")
                        .WithMany("TransactionCategories")
                        .HasForeignKey("ExternalTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MakeMeRich.Domain.Entities.FinancialCategory", "FinancialCategory")
                        .WithMany("ExternalTransactionCategories")
                        .HasForeignKey("FinancialCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExternalTransaction");

                    b.Navigation("FinancialCategory");
                });

            modelBuilder.Entity("MakeMeRich.Domain.Entities.FinancialTransactionCategories.InternalTransactionCategory", b =>
                {
                    b.HasOne("MakeMeRich.Domain.Entities.FinancialCategory", "FinancialCategory")
                        .WithMany("InternalTransactionCategories")
                        .HasForeignKey("FinancialCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MakeMeRich.Domain.Entities.FinancialTransactions.InternalTransaction", "InternalTransaction")
                        .WithMany("TransactionCategories")
                        .HasForeignKey("InternalTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinancialCategory");

                    b.Navigation("InternalTransaction");
                });

            modelBuilder.Entity("MakeMeRich.Domain.Entities.FinancialTransactions.ExternalTransaction", b =>
                {
                    b.HasOne("MakeMeRich.Domain.Entities.FinancialAccount", "FinancialAccount")
                        .WithMany("ExternalTransactions")
                        .HasForeignKey("FinancialAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinancialAccount");
                });

            modelBuilder.Entity("MakeMeRich.Domain.Entities.FinancialTransactions.InternalTransaction", b =>
                {
                    b.HasOne("MakeMeRich.Domain.Entities.FinancialAccount", "ReceivingAccount")
                        .WithMany("ReceivedInternalTransactions")
                        .HasForeignKey("ReceivingAccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MakeMeRich.Domain.Entities.FinancialAccount", "SendingAccount")
                        .WithMany("SendedInternalTransactions")
                        .HasForeignKey("SendingAccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ReceivingAccount");

                    b.Navigation("SendingAccount");
                });

            modelBuilder.Entity("MakeMeRich.Domain.Entities.FinancialAccount", b =>
                {
                    b.Navigation("ExternalTransactions");

                    b.Navigation("ReceivedInternalTransactions");

                    b.Navigation("SendedInternalTransactions");
                });

            modelBuilder.Entity("MakeMeRich.Domain.Entities.FinancialCategory", b =>
                {
                    b.Navigation("ExternalTransactionCategories");

                    b.Navigation("InternalTransactionCategories");
                });

            modelBuilder.Entity("MakeMeRich.Domain.Entities.FinancialTransactions.ExternalTransaction", b =>
                {
                    b.Navigation("TransactionCategories");
                });

            modelBuilder.Entity("MakeMeRich.Domain.Entities.FinancialTransactions.InternalTransaction", b =>
                {
                    b.Navigation("TransactionCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
